### ISSUE TITLE
unable to find API to send MFA Enroll activation link via email/sms 

### ISSUE THREAD

**Issue by snehas13** [okta/okta-auth-java#107]
Unable to find API to send an activation email when when the user is unable to scan the QR code provided as part of an Okta Verify transaction. If for any reason the user can't scan the QR code, they can use the link provided in email to complete the transaction during multi factor enrolment setup.

I didn't find any direct api wrapper for below REST api in android
https://${yourOktaDomain}/api/v1/authn/factors/opfh52xcuft3J4uZc0g3/lifecycle/activate/email

Able to locate below API in Swift, but unable to find for android.
sendActivationLinkViaEmail
https://github.com/okta/okta-auth-swift

**Comment by VitaliiTytarenko-okta** [comment]
Hello @snehas13 
Thanks for your question.
If your question is Android related, you better post it in [okta-oidc-android](https://github.com/okta/okta-oidc-android).
Could you please clarify which factor are you using? Have you checked this [Factor lifecycle operations](https://developer.okta.com/docs/reference/api/factors/#factor-lifecycle-operations)?
I'll investigate your question and I'll get back to you when I have more information.

**Comment by snehas13** [comment]
@VitaliiTytarenko-okta 
We are using the same okta java lib in our android project
    implementation "com.okta.authn.sdk:okta-authn-sdk-api:$okta_sdk_Api"
    implementation "com.okta.authn.sdk:okta-authn-sdk-impl:$okta_sdk_impl"

We are using below authentication client interface and i need to know the method in this interface which will verify activation via email/sms

https://developer.okta.com/okta-auth-java/development/apidocs/index.html?com/okta/authn/sdk/client/AuthenticationClient.html

**Comment by VitaliiTytarenko-okta** [comment]
We will implement this soon.
Internal ref: `OKTA-406538`.
Thanks for using Okta!
