### ISSUE TITLE
Error while updating Plaid SDK 3.5.0 (Duplicate class org.bouncycastle.LICENSE)

### ISSUE THREAD

**Issue by RajaReddyP** [okta/okta-auth-java#110]
In my application, we are using OKTA SDK (it has a dependency on the bouncy-castle) along with Plaid, If I try to update plaid SDK to the latest 3.5.0 we are facing issues like below. 

**Error:**Duplicate class org.bouncycastle.LICENSE found in modules jetified-bcprov-jdk14-1.69 (org.bouncycastle:bcprov-jdk14:1.69) and jetified-bcprov-jdk15on-1.64 (org.bouncycastle:bcprov-jdk15on:1.64)

Currently, we are using: **Plaid SDK-3.2.2**
**OKTA auth SDK-2.0.0**

**Comment by arvindkrishnakumar-okta** [comment]
@RajaReddyP yes, `com.okta.authn.sdk:okta-authn-sdk-android` has a `runtime` dependency on bouncycastle lib.

![image](https://user-images.githubusercontent.com/61501885/129938278-71c44bab-9f67-42bf-8308-3c19afacbcc0.png)

You should try excluding this dependency in one of the SDKs.

**Comment by bdemers** [comment]
I'm not sure what the `jetified-` prefix is for, but here is a general answer:

IIRC, bouncy castle produces different artifacts targeted to different JVMs
So in your case you have one lib pulling in a JDK 1.4 lib: `bcprov-jdk14`, and this library using the `jdk15on` (for Java 1.5+),

I'd suggest attempting to exclude the `-jdk14` libs from your classpath first and see if that solves the problem.

It would also be helpful to know what is triggering that error message?  I'm guessing you have an enforcer rule to block duplicate classes? Or maybe you are using the shade plugin?

**Comment by JayNewstrom** [comment]
jetified is an android thing. You can force a specific version in gradle:
