### ISSUE TITLE
Missing nullability annotations in AuthenticationStateHandler

### ISSUE THREAD

**Issue by sannyo** [okta/okta-auth-java#129]
### I'm submitting a
  - [ ] bug report
  - [ x] feature request

### Background info

Would like to have @Nullable and @NotNull annotations so when using the SDK with Kotlin would not need to use nullable params in the AuthenticationStateHandler implementation to ensure that it is truly non null.

### Expected behavior

When using Kotlin and implementing AuthenticationStateHandler interface would tell if AuthenticationResponse is nullable or non null for sure.

What should have happened? 

### What went wrong?

Please provide log or error messages if applicable.

### Steps to reproduce

Use Kotlin and create an implementation of the interface.

### SDK Version
2.0.0

**Comment by arvindkrishnakumar-okta** [comment]
@sannyo Thanks for posting!

We can definitely add the annotations to `AuthenticationStateHandler`. You can safely assume that `AuthenticationResponse` would be `@NotNull` in all cases.

**Comment by sannyo** [comment]
> @sannyo Thanks for posting!
> 
> We can definitely add the annotations to `AuthenticationStateHandler`. You can safely assume that `AuthenticationResponse` would be `@NotNull` in cases where you handle the response inside `AuthenticationStateHandler`.
> 
> Internal Ref: OKTA-460846

Thank you for your fast reply.

**Comment by arvindkrishnakumar-okta** [comment]
Resolved by https://github.com/okta/okta-auth-java/pull/130.
