### ISSUE TITLE
Need an AuthenticationBuilder

### ISSUE THREAD

**Issue by mfulgo** [okta/okta-auth-java#13]
It would be helpful if there was an `AuthenticationBuilder`, similar to the `UserBuilder` of the `okta-sdk-api`.

If one wants to create an authentication proxy or broker application, they need to craft their own `AuthenticationRequest` with a context (deviceToken) and options. So, the `client.authenticate(username, password, relayState, handler)` method doesn't cut it.

Also, I believe we'd need a way to set the `User-Agent` and `X-Forwarded-For` headers on each request. (Perhaps this should be a separate issue.)

**Comment by bdemers** [comment]
Great idea! 
Currently you can chain the methods though, so something link:

```java
AuthenticationRequest request = authenticationClient.instantiate(AuthenticationRequest.class)
                .setRelayState("some-relay-state")
                .setUsername("joe.coder@example.com");
```
It requires a few extra lines though, are you thinking something like:

```java
AuthenticationRequest request = AuthenticationRequestBuilder.instance()
                .setRelayState("some-relay-state")
                .setUsername("joe.coder@example.com")
                .build();
```

To customize the user-agent just implement a `UserAgentProvider` similar to this one: [`AuthnSdkUserAgentProvider`](https://github.com/okta/okta-auth-java/blob/master/impl/src/main/java/com/okta/authn/sdk/impl/http/AuthnSdkUserAgentProvider.java)

`X-Forwarded-For` is a little tricker, can you explain that use case in a little more detail?

**Comment by mfulgo** [comment]
Thanks, I found the `instantiate` method a little later on. Might be good to add to the readme. It's a viable work-around for now.

A small thing that I ran into with that was when instantiating a subclass, the order of setter calls matters:
```java
// Works
client.instantiate(VerifyPassCodeFactorRequest.class)
  .setPassCode(passCode)
  .setStateToken(token);

// Does not compile
client.instantiate(VerifyPassCodeFactorRequest.class)
  .setStateToken(token) // returns a VerifyFactorRequest
  .setPassCode(passCode); // No such method on VerifyFactorRequest
```

My app is essentially acting as a login portal / gateway...
The `X-Forwarded-For` header requirement comes from the [Okta API docs](https://developer.okta.com/docs/api/getting_started/design_principles#ip-address) ([See also.](https://developer.okta.com/docs/api/resources/authn#primary-authentication-with-trusted-application)):
> Okta supports the standard `X-Forwarded-For` HTTP header to forward the originating client’s IP address if your application is behind a proxy server or acting as a login portal or gateway. 

[Similarly](https://developer.okta.com/docs/api/getting_started/design_principles#user-agent), I need to set the `User-Agent` *per request*, which looks like it gets a bit tricky with the `AuthnSdkUserAgentProvider`:
> If your application is acting as a gateway or proxy, you should forward the `User-Agent` of the originating client with your API requests.

**Comment by bdemers** [comment]
All good points.
I'll get back to you on the headers 🤔

**Comment by jmalickenexient** [comment]
@bdemers What is the update on this? The ability to send a X-Forwarded-* header and User-Agent header containing the originating client User-Agent is needed to follow the Okta guidance on implementing a gateway application like @mfulgo mentioned.

**Comment by bdemers** [comment]
@jmalickenexient no update yet.

Your comment will help us prioritize this though, Thanks!

**Comment by robertjd** [comment]
@bdemers does this new README section cover what was needed by this issue? https://github.com/okta/okta-auth-java#setting-request-headers-parameters-and-device-fingerprinting

**Comment by mfulgo** [comment]
From my perspective, I think this issue is addressed with the `RequestContext` and the new README section.
