### ISSUE TITLE
Support setting X-Forwarded-* headers

### ISSUE THREAD

**Issue by bdemers** [okta/okta-auth-java#16]
Based on comments from #13 and #14 from @mfulgo

Setting a `X-Forwarded-For` header is required for this scenario. 

(comments welcome)

**Comment by bdemers** [comment]
@mfulgo Let's chat about this use case a little more on this issue.

How much are you tweaking the response bodies when proxying the requests?  Is it a straight proxy, or are you supporting a migration scenario ?

**Comment by mfulgo** [comment]
It's not a straight proxy: I'm expecting to drop the links and some other fields from the responses, as I expect the client application to know and follow a certain flow, and I don't want to expose the Okta endpoint URL.

I also need to do some custom validation of phone numbers used for SMS factors, which is one of the primary reasons for doing the proxy.

**Comment by bdemers** [comment]
Thanks! that helps!

**Comment by jmalickenexient** [comment]
Any update here? I've looked through the docs and library and sadly it looks like I'd have to hack the inner-guts to send a X-Forwarded-* header (which is not easily feasible and comes with a host of its own problems). Appreciate your hard work on this library and any updates you have to share.

**Comment by bdemers** [comment]
Nothing yet, what are you currently doing? maybe we can provide another option?

**Comment by mfulgo** [comment]
Thanks, @bdemers!

**Comment by jmalickenexient** [comment]
Thank you @bdemers !!
