### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by AyaanMahir** [okta/okta-auth-java#46]
I am trying to setup this project as maven to try out the examples for my usecase implementation understanding, 
However, I am facing the build error complaining the lifecycle configuration related to the derived parent pom(okta-parent) for the below goals. could you point me where i am going wrong.
<execution>
                        <goals>
                            <goal>addSources</goal>
                            <goal>addTestSources</goal>
                            <goal>generateStubs</goal>
                            <goal>compile</goal>
                            <goal>generateTestStubs</goal>
                            <goal>compileTests</goal>
                            <goal>removeStubs</goal>
                            <goal>removeTestStubs</goal>
                        </goals>
                    </execution>

**Comment by bdemers** [comment]
Hey @AyaanMahir!

What versions are you using (maven, Java, this project)?  Are you trying to build master, or including the dependent in your project?  What error message are you seeing?

**Comment by AyaanMahir** [comment]
Thank  you for the quick reply!
I am trying to build the master for now, Maven version is - 3.3.9 and java is 1.8. 
The project where i will be including is also having the maven version as 3.3.9 , but java is 1.7 ., please let me know if any concerns with the versions. The issue seems to be more with Maven version only. 

The error shows  <parent> tag of individual modules:
Plugin execution not covered by lifecycle configuration: org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:removeTestStubs (execution: default, phase: test-compile)
Plugin execution not covered by lifecycle configuration: org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:compile (execution: default, phase: compile)
Plugin execution not covered by lifecycle configuration: org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:removeStubs (execution: default, phase: compile)
Plugin execution not covered by lifecycle configuration: org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:addTestSources (execution: default, phase: initialize)
Plugin execution not covered by lifecycle configuration: org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:compileTests (execution: default, phase: test-compile)

**Comment by bdemers** [comment]
Try using `./mvnw` script instead, that will use 3.6.0
You will also need at least Java 1.8.

Generally you don't need to build the project (unless you are trying fork or submit patches)
You can see a servlet example that uses the project here: https://github.com/okta/samples-java-servlet

That said, if you want to build it, please attach the full maven log and i should be able to point you in the right direction

**Comment by AyaanMahir** [comment]
Ok., Thank you Brian!!
