### ISSUE TITLE
AuthenticationClients.builder().build() doesn't work

### ISSUE THREAD

**Issue by vekdeq** [okta/okta-auth-java#53]
Hi There, 

Firstly, I am comparing this with okta-sdk-java api as both APIs as necessary for our Legacy Spring Boot based integration with Okta. We are moving away from our current IS / SSO provider to Okta. To minimize the migration efforts, we are leveraging both these APIs where in :

1. We are getting com.okta.sdk.client.Client bean injected directly through OktaSdkConfig for SDK api - which takes care of configuring client pointing to below properties 
okta.client.token=yyyyyyy
okta.client.orgUrl=https://xxxxx.oktapreview.com

2. There is nothing similar to get com.okta.authn.sdk.client.AuthenticationClient bean  like OktaSdkConfig in auth API. Hence when, we use

@Bean
  public AuthenticationClient getOktaAuthenticationClient() {
      return AuthenticationClients.builder().build();
  }
 it doesn't pick up the the Org URL & token configured in app.prop file and fails with 
 threw exception; nested exception is java.lang.IllegalArgumentException: Okta org url must not be null.

Am I missing something ? I am using 1.0.0 version. API docs says - your prop files needs to be configured as above. Please guide.

**Comment by bdemers** [comment]
Correct, we don't have explicit support for the AuthenticationClient as starter/auto config.

Your best bet would be to inject the `OktaClientProperties` bean, something very similar to what you have now:

```java
@Bean
public AuthenticationClient oktaAuthenticationClient(OktaClientProperties clientProperties) {
return AuthenticationClients.builder()
    .setOrgUrl(clientProperties.getOrgUrl())
    .build();
} 
```
**NOTE:** from memory, so there might be a typo

This is very similar to how the `OktaSdkConfig` class works for the management client.

There are a few other ways to configure the SDKs, but this option is _most_ inline with a Spring configuration.

Keep us posted!

**Comment by vekdeq** [comment]
Alright !! Thanks .. It is working - I mean deployment went through. I yet have to use it in actual api call. I guess - it doesn't need API token unlike SDK Client to make those call - correct ?

**Comment by bdemers** [comment]
Correct, the /authn API's do NOT need an API key

Thanks for following up!

**Comment by vekdeq** [comment]
Brian, quick follow-up question 

How to get AuthenticationResponse object using this API, if I don't have id / pwd in my spring boot app. I do have Authentication Object in SecurityContext - which don't provide me id_token, which I need for logout URL configuration. Any help / guidance appreciated ..

**Comment by bdemers** [comment]
@vekdeq
I’m not sure what you are asking, you mentioned an id_token?  This library doesn’t handle OAuth flows. Are you asking about our Spring Boot Starter?

**Comment by vekdeq** [comment]
Yes, that's correct. We have a Spring Boot based app using Okta Spring Boot Starter, Okta-Java-SDK, Okta-Authn-Java API calls. We are looking to implement logout functionality - which includes killing app session as well as Okta session too. To kill Okta Session we need to need to  implement Okta logout using https://YYYY.oktapreview.com/oauth2/v1/logout?id_token_hint=XXXX api call from Spring boot app. I guess this function is not provided as part of any of APIs and we need to make a get / post call to logout from our middleware (Spring boot app). How to get id_token for that call ? Is there any other way to logout ?

Thanks a bunch in advance 

Vivek

**Comment by bdemers** [comment]
@vekdeq
RP initiates logout is also part of the next Spring Security release. (This lib just sits on top of Spring Sec)
https://spring.io/blog/2019/04/16/spring-security-5-2-0-m2-released

**Comment by vekdeq** [comment]
Hi Brian, 

Even after upgrading to Spring Security 5.2.0.M4 the logout is not clearing Okta session. I have updated this in Spring Security Issue as well as below;

We have spring boot based application(s) using Okta as IDP, using okta spring boot starter - which inject Spring Security 5.1.5. With some efforts, I was able to configure gradle script where in my WAR file now have Spring Security 5.2.0.M4 jars. I am still unable to clear / kill Okta Session - after hitting default logout url. It is configured as link (app/logout) on app's UI - so no XHR - just link. Am I missing anything ?

Please guide. 

Vivek

**Comment by bdemers** [comment]
@vekdeq Lets move your Spring related questions to okta/okta-spring-boot or for more general suggestions the [Developer Forum](https://devforum.okta.com/)
