### ISSUE TITLE
Authentication of Staged user

### ISSUE THREAD

**Issue by vekdeq** [okta/okta-auth-java#55]
Hi Team, 

I am looking to authenticate staged user. The use case, we have of an existing applications where we are moving away from current IDP to Okta. We have flow like below;

1. User self registers to the application online (No Okta interaction at this time). It creates a registration request, which needs to be reviewed and approved by staff.
2. Internal staff reviews and approves the request through intranet based internal application (based on certain legal requirements). On approval, we are creating Okta user with staged status. As part of approval, the email is triggered to end user to complete the registration to the site - which includes setting user profile in our datastore and then activate the User in Okta. 
3. The okta user creation in step # 2 includes temp password, which needs to be authenticated by user. Only after that, user will setup permanent password of his choice to make user creation complete. That's where, we are calling auth API call with User id & Pwd of staged user, which is failing. If we change the status as active (through OKTA site) - auth call works as expected. So we need to auth user in a case, where it's status is staged. 

Please guide, if we are doing something wrong here. 

Vivek Bedekar

**Comment by bdemers** [comment]
Hey @vekdeq!

What call is failing? What is the error you are seeing?  What have you tried so far?

**Comment by vekdeq** [comment]
Hi Brian, 

Thanks for quick response !! Here is the code : 

public boolean isUserAuthenticated(String uid, String pwd) {
		try {
			AuthenticationResponse response = oktaAuthClient.authenticate(uid, pwd.toCharArray(), null, null);
			if (response !=null && response.getSessionToken() !=null && response.getStatus() == AuthenticationStatus.SUCCESS) {
				return true;
			} else {
				return false;
			}
		} catch (AuthenticationException e) {
			LOGGER.error("---- Unable to Authenticate User : ----"+ uid, e);
			return false;
		}		 
	}

We are getting AuthenticationException. The moment, we activate user from Okta Portal - it goes through. The exception trace is as below : 

 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.okta.sdk.resource.ResourceException: HTTP 401, Okta E0000004 (Authentication failed), ErrorId oaecVQ9r54bStaWdl1SHc4yyQ
        at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:453)

Okta Support replied  to case just now: 

When a user has a staged status, it needs to be activated first with : https://developer.okta.com/docs/reference/api/users/#activate-user , and only then the auth will work.

So it seems we hit the roadblock now. 

Vivek V. Bedekar

**Comment by bdemers** [comment]
Are you using the temporary password for this attempt?

**Comment by vekdeq** [comment]
Yeah - the pwd which we / application create as part of createUser Api call as below :

 String tempPwd = generatePassword(10);
		 UserBuilder.instance()
					.setEmail(email)
			    	.setFirstName(firstname)
			    	.setLastName(lastName)
			    	.setLogin(email)
			    	.setPassword(tempPwd.toCharArray())
			    	.setActive(false)
			    	//.addGroup(TODO)
			    	.buildAndCreate(oktaClient);		

		 return tempPwd;

**Comment by bdemers** [comment]
this inactive user was allowed to authenticate in other places?  Or are the users ACTIVE when you attempt to login directly with Okta?

**Comment by vekdeq** [comment]
It's not inactive user - the status says staged on OKTA dashboard below. Should I try creating without - .setActive(false) ?

Test DRO DEV909@MYDEQTEST.COM | DEV909@MYDEQTEST.COM | Staged
-- | -- | --
  | TEST RCO QA102@MYDEQTEST.COM | QA102@MYDEQTEST.COM | Staged

**Comment by bdemers** [comment]
Yes, `.setActive(true)` would allow the user to login

**Comment by vekdeq** [comment]
yeah - but don't want user to do that - till he complete other formalities which are built as part of account setup app/flow on our side. Hence, we need temp pwd to authenticate user and then force him to complete account setup includes - setting permanent pwd & other steps. Till that time, we were hoping to keep user in staged status and activate after account set up is complete. 

The reason, for not activating upfront is - user can then log in actual site using temp pwd (without completing other legal formalities). I think, I got a work around to it as below;

activate user on approval - but don't add user to group - Only Okta User.
add to group & apps - on completing account setup. - Okta + Our Apps. 

I hope it works : Question on that.
How to add groups dynamically - do you have any property file configuration for that ? As Grp ID will be different for environments. 

Vivek V.  Bedekar

**Comment by bdemers** [comment]
@vekdeq I'm not sure I'm following, you want the user to be able to login from one place but not another?

I think you will need to take another approach, like a role/group check.

You should also take a look at our new Hooks (specifically the registration hook: https://developer.okta.com/docs/reference/registration-hook/#see-also)

**Comment by bdemers** [comment]
I'm going to close this issue, as this is the intended result (you cannot login with a user that is deactivated)
