### ISSUE TITLE
Issues with Android and possibly null session token

### ISSUE THREAD

**Issue by mdeveracoding** [okta/okta-auth-java#58]
All,

We are currently having login issues with Pixel 3 phones with Android 10.  Build number QP1A.191005.007.  The problem is that we have other Pixel phones of similar models and build numbers that don't have any login issues.  When we do have a login issue we start to see logs indicating that the session token is null.  The version of Okta libraries that we are using is listed below:

```
com.okta.android:oidc-android:1.0.3
com.okta.authn.sdk:okta-authn-sdk-api:0.4.0
com.okta.authn.sdk:okta-authn-sdk-impl:0.4.0
com.okta.sdk:okta-sdk-okhttp:1.5.2
```

Has anyone been experiencing this issue?  We are trying to debug our code using the correct Okta config for development and/or production.  But we can't replicate a null session token and our test/production users login just fine.

Thanks for any tips or guidance.

**Comment by FeiChen-okta** [comment]
Hi @mdeveracoding You should update the oidc-android client to 1.0.8
The issue with Android 10 is fixed in the latest release.
