### ISSUE TITLE
Application crash with okta-sdk-okhttp version: 1.6.0

### ISSUE THREAD

**Issue by RajaReddyP** [okta/okta-auth-java#64]
When I updated **okta-sdk-okhttp** version to **1.6.0** application crashing. 

**implementation "com.okta.sdk:okta-sdk-okhttp:1.6.0"**

**Logs:** 

```
Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex) 
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:149) 
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:183) 
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:115) 
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>
```

I didn't get proper documentation with this latest version, Can you please help to resolve this.

**Comment by RajaReddyP** [comment]
Hi @bdemers  Yes, I am using these 4 libs 

`implementation "com.okta.android:oidc-androidx:1.0.13"
  implementation "com.okta.authn.sdk:okta-authn-sdk-api:1.0.0"
  implementation "com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0"
  implementation "com.okta.sdk:okta-sdk-okhttp:1.5.4"`

`okta-sdk-okhttp:1.5.4` working fine if I change to 1.6.0, application crashing.

**Comment by bdemers** [comment]
My suggestion is to stick with the current version until we push out an update that uses 1.6

**Comment by cah-andrew-fitzgerald** [comment]
I'm also running into issues with sdk version 1.6.0 and Authn version 1.0.0

This snippet fails with `java.lang.ClassNotFoundException: com.okta.sdk.impl.util.BaseUrlResolver` (It looks `BaseUrlResolver` was moved to `com.okta.commons.http.config`)
```java
        Client oktaSdk = Clients.builder()
                .setOrgUrl(oktaDomain)
                .setClientCredentials(new TokenClientCredentials(oktaToken))
                .build();

        AuthenticationClient oktaAuth = AuthenticationClients.builder()
                .setOrgUrl(oktaDomain)
                .build();
```



For now it make sense to add a note to the readme informing users which version of the SDK this repo tests against

**Comment by bdemers** [comment]
Thanks @cah-andrew-fitzgerald! We will be working on updating this soon, and we will get the README updated!

cc: @arvindkrishnakumar-okta

**Comment by LDNV** [comment]
Hello, I'm getting the same crash as the first poster in this thread:

**With "com.okta.sdk:okta-sdk-okhttp:1.5.4"**

`java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)`

**With "com.okta.sdk:okta-sdk-okhttp:1.6.0"**
` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: java.lang.IllegalStateException: Unable to find a 'com.okta.sdk.impl.http.RequestExecutorFactory' implementation on the classpath.  Please ensure you have added the okta-sdk-httpclient.jar file to your runtime classpath.`

The code that causes this crash is the following:

```Kotlin 
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        AuthenticationClients.builder()
            .setOrgUrl("https://www.google.com")
            .build()
    }
}
```

I think this crash might be related to the gradle plugin version I'm using, here is my set up:

**gradle-wrapper.properties:**
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**build.gradle(project):**
classpath "com.android.tools.build:gradle:4.0.1"

**build.gradle(app):**
``` ruby
compileOptions{
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
```

I'm attaching the sample project where I get this crash.

[MyApplication2.zip](https://github.com/okta/okta-auth-java/files/4950113/MyApplication2.zip)

**Comment by bdemers** [comment]
Hi @LDNV 

Of note: the httpclient `AllowAllHostnameVerifier ` issue is an Android issue (IIRC, Android ships with an unsupported fork of Apache Http Client).
This is why we also support ok-http.

If use use version `1.5.4` of `okta-sdk-okhttp` does that work for you?
We are in the process of updating the dependencies of in this library, cc @arvindkrishnakumar-okta

**Comment by LDNV** [comment]
@bdemers  no, the same crash happens even when I use `com.okta.sdk:okta-sdk-httpclient:1.5.4`. 
According to the Android documentation over here:

https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p

"_Beginning with Android 9, that library is removed from the bootclasspath and is not available to apps by default._"

If I set my gradle file like this:
```ruby
android {
    compileSdkVersion 29
    buildToolsVersion "30.0.1"

    defaultConfig {
        applicationId "com.example.myapplication"
        minSdkVersion 28
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
    }
}
```

I shouldn't have any issues with  the legacy apache library being added to the project, and the dependency tree can only find apache dependencies coming from  'com.okta.sdk:okta-sdk-httpclient:1.5.4' 

You can check the full scan over here:
https://scans.gradle.com/s/ldqeyckdz3mcg/dependencies?expandAll

**Comment by bdemers** [comment]
@LDNV 

This error: 
```
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
```
Shows the HttpClient class getting pulled in from `framework.jar`.

If you are using the `ok-http` client you can exclude the httpclient dependency, your dependencies could looks something like this;

```groovy
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:1.0.0'
    implementation('com.okta.authn.sdk:okta-authn-sdk-impl:1.0.0') {
        exclude group: 'com.okta.sdk', module: 'okta-sdk-httpclient'
    }
    implementation 'com.okta.sdk:okta-sdk-okhttp:1.5.4'
```

We will make sure you don't need to add this exclusion in our next release.

A question to you, would prefer to have a dependency that had an `android` tag on it?
```groovy
    implementation 'com.okta.authn.sdk:okta-authn-sdk-android:<version>'
```

**Comment by LDNV** [comment]
@bdemers  Thanks for your quick reply.

 After doing some more research I think that you are right, even if the apache libs are not available for the app in more recent versions of Android, the jar is still included in the framework, taking precedence over a more updated version declared as a dependency in the app's gradle files.

And yes it's working for me now if I use ok-hhtp, I think I just needed to add this part `exclude group: com.okta.sdk', module: 'okta-sdk-httpclient'`

To answer your last question, I think it would be helpful to have an android tag in the dependency, specially because we are redirected to 
https://github.com/okta/okta-auth-java

from the Android specific oicd lib:
https://github.com/okta/okta-oidc-android#sign-in-with-your-own-ui
