### ISSUE TITLE
DefaultAuthenticationResponse(InternalDataStore dataStore) is missing.

### ISSUE THREAD

**Issue by asukhyy** [okta/okta-auth-java#7]
For some reason `com.okta.sdk.ds.DataStore#instantiate` method cannot do work for `DefaultAuthenticationResponse` resource.

Error:
`java.lang.NoSuchMethodException: com.okta.authn.sdk.impl.resource.DefaultAuthenticationResponse.<init>(com.okta.sdk.impl.ds.InternalDataStore)`

**Comment by bdemers** [comment]
@asukhyy which version are you using?  Do you have a full stacktrack?

**Comment by bdemers** [comment]
(clicked wrong button, reopened)

**Comment by asukhyy** [comment]
@bdemers latest release version  **0.1.0**, jdk version **1.8.0_162**

It is easy to reproduce by next code snippet:

```
import com.okta.authn.sdk.client.AuthenticationClient;
import com.okta.authn.sdk.client.AuthenticationClients;
import com.okta.authn.sdk.resource.AuthenticationResponse;

public class Main {
	public static void main(String[] args) {
		AuthenticationClient client = AuthenticationClients.builder()
			.setOrgUrl("http://any.tld")
			.build();

		AuthenticationResponse response = client.instantiate(AuthenticationResponse.class);
	}
}
```

**Comment by bdemers** [comment]
@asukhyy thanks! can you include your pom dependencies?

**Comment by asukhyy** [comment]
```
		<dependency>
			<groupId>com.okta.sdk</groupId>
			<artifactId>okta-sdk-api</artifactId>
			<version>${okta.version}</version>
		</dependency>
		<dependency>
			<groupId>com.okta.authn.sdk</groupId>
			<artifactId>okta-authn-sdk-api</artifactId>
			<version>${okta.authn.version}</version>
		</dependency>
		<dependency>
			<groupId>com.okta.authn.sdk</groupId>
			<artifactId>okta-authn-sdk-impl</artifactId>
			<version>${okta.authn.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.okta.sdk</groupId>
			<artifactId>okta-sdk-impl</artifactId>
			<version>${okta.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.okta.sdk</groupId>
			<artifactId>okta-sdk-httpclient</artifactId>
			<version>${okta.version}</version>
			<scope>runtime</scope>
		</dependency>
```
where 
```<okta.version>1.1.0</okta.version>
<okta.authn.version>0.1.0</okta.authn.version>
```

**Comment by bdemers** [comment]
@asukhyy  Sorry for the delay,

The `AuthenticationResponse` class requires a payload when constructing which isn't compatible with the `instantiate` method.

You could call something like: `AuthenticationResponse response = client.authenticate(...)` to get a response object back.

Does that help?

**Comment by asukhyy** [comment]
@bdemers no really, just noticed that other responses have constructor with single argument of type `com.okta.sdk.impl.ds.InternalDataStore`, for example `com.okta.sdk.impl.resource.session.DefaultSession#DefaultSession(com.okta.sdk.impl.ds.InternalDataStore)`.

**Comment by bdemers** [comment]
The response [only] objects are constructed internally and populated with a map (based on the json response) before being returned.

For testing purposes i'd recommend using something like Mockito (or easy mock) to create objects.  That said if this pattern is blocking you from doing something please let us know!

**Comment by asukhyy** [comment]
@bdemers I'm trying to use latest okta skds but also for backward compatibility previous not compatible on source code level okta skd is in use.

During migration period both sdks are present but only domain objects from latests sdks are exposed therefore domain objects from previous are adapted to latest one - therefore I need possability to instantiate them.
As result to instantiate latest domain objects `instantiate` method is used and this issue appears. I have workaround for that just using casting to have `com.okta.sdk.impl.ds.InternalDataStore#instantiate` where I can pass empty map.

**Comment by bdemers** [comment]
@asukhyy that works!

I'd like to hear more about how you migrating.  I'm trying to put together a quick migration doc

**Comment by asukhyy** [comment]
@bdemers just using standard adapter pattern  where adaptee is previous version of Okta SKD, therefore to return new domain objects `instantiate` method is used and properties are set via `setProperty` method. Is it answer on your question?

**Comment by bdemers** [comment]
Using `InternalDataStore#instantiate` is sounds like a good short term migration strategy. Going to close this issue.

Please reopen if you feel otherwise
