### ISSUE TITLE
AuthenticationClient caching user when creating OIDC access tokens

### ISSUE THREAD

**Issue by landon-shumway** [okta/okta-auth-java#72]
We found an issue where we attempted to create OIDC access tokens for several users in our account, but when we use these access tokens to get the user's profile information it always returns the same user info for the first user we authenticate using the AuthenticationClient. We create a session token using the following command: 
```
private String createSession(User user) {

  AuthenticationResponse loginResponse = AuthenticationClients.builder()
  .setOrgUrl(OKTA_ORG_URL)
  .build()
  .authenticate(user.getEmail(), user.getPassword(), null, null);

  if (AuthenticationStatus.SUCCESS.equals(loginResponse.getStatus())) {
                  return loginResponse.getSessionToken();
              }
}
```
We call this function for several of our Okta users, we then use these session tokens to generate access tokens using the `/oauth2/v1/authorize` endpoint, the access tokens are successfully generated, and we can call the `/oauth2/v1/userinfo` endpoint with each access token to get back user info, but every access token always returns the same user profile, and it is always returns whomever the first user was to have a session token generated for them (we confirmed this by testing several different permutations).

We fixed our issue by pivoting away from the AuthenticationClient and just calling the `/api/v1/authn` endpoint directly, and our access tokens now return the expected user profiles. Not sure if others have experienced this issue, but we didn't see any previous issue created for this. We tried referencing the Java Docs for the AuthenticationClientBuilder here: https://developer.okta.com/okta-auth-java/development/apidocs/index.html?com/okta/authn/sdk/client/AuthenticationClientBuilder.html
which makes a reference to a caching section:
>"Understanding caching is extremely important when creating a AuthenticationClient instance, so please ensure you read the Caching section below."

 However, that section appears to be missing from the docs so we were unable to determine if there was a configuration issue we were missing on our end.

**Comment by bdemers** [comment]
Thanks @landon-shumway! This is NOT expected, caching is actually disabled:
https://github.com/okta/okta-auth-java/blob/master/impl/src/main/java/com/okta/authn/sdk/impl/client/DefaultAuthenticationClient.java#L68

The Javadoc is wrong, we will fix that (it was likely a copypasta from our Management SDK)

As for the cache issue, do you have any `OKTA_*` environment variables, or a `~/.okta/okta.yaml` file.

**Comment by landon-shumway** [comment]
We do not. We only set the URL to our Okta account which is defined as a static constant in the same Java class as that code snippet (OKTA_ORG_URL).

**Comment by arvindkrishnakumar-okta** [comment]
@landon-shumway Thanks for raising this! Just so I understand the issue better, how are you executing the `/oauth2/v1/authorize` call and the next `/oauth2/v1/token` call? In other words, I assume the Auth SDK is used only for the first session token call, right?

**Comment by landon-shumway** [comment]
@arvindkrishnakumar-okta We use RestTemplate to call the /oauth2/v1/authorize endpoint, and then we extract the access token from the location header (this snippet if pulled together from several functions, so I apologize if I'm missing a step here):
```
ResponseEntity<String> response = restTemplate.exchange(authorizeUrl, HttpMethod.GET, entity, String.class);
URI location = response.getHeaders().getLocation();
 List<NameValuePair> queryValues = URLEncodedUtils.parse(location.getFragment(), Charsets.UTF_8);
 Optional<NameValuePair> accessToken =
     queryValues.stream().filter(x -> x.getName().equals(ACCESS_TOKEN_NAME)).findFirst();


return accessToken.get().getValue();
```

Yes, we are only using the Auth SDK to generate the OIDC  session token. All of our other calls to Okta are made through RestTemplate.

**Comment by arvindkrishnakumar-okta** [comment]
@landon-shumway is this still an issue?

Feel free to reopen with comments if needed.
