### ISSUE TITLE
forgot password with trusted application

### ISSUE THREAD

**Issue by garcger-blk** [okta/okta-auth-java#76]
What is the correct way of making the following call via the auth sdk?

```
curl -v -X POST \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: SSWS ${api_token}" \
-H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36" \
-d '{
  "username": "no@one.com"
}' "https://${yourOktaDomain}/api/v1/authn/recovery/password"
```

The 3 approaches below all result in `com.okta.sdk.resource.ResourceException: HTTP 403, Okta E0000006 (You do not have permission to perform the requested action), ErrorId oaeKo877F3cSvuSpMIaOBx60g`

**1**
```java
AuthenticationResponse authResponse = authenticationClient.recoverPassword("no@one.com", null, null, null);
```

**2**
```java
AuthenticationResponse authResponse = authenticationClient.recoverPassword(authenticationClient
		.instantiate(RecoverPasswordRequest.class)
		.setUsername("no@one.com"), null);
```

**3**
```java
ExtensibleResource body = authenticationClient.instantiate(ExtensibleResource.class);
body.put("username", "no@one.com");
AuthenticationResponse authResponse = authenticationClient
		.getDataStore().http().setBody(body).post("/api/v1/authn/recovery/password",
				AuthenticationResponse.class);
```

**Comment by bdemers** [comment]
You have a couple of different options depending on the type of application you are building
If you are using the /authn API for this request, you would need to include the SSWS token in this request.

https://github.com/okta/okta-auth-java/blob/master/api/src/main/java/com/okta/authn/sdk/client/AuthenticationClient.java#L287

Which would be something like:
```java
authenticationClient.recoverPassword(
    authenticationClient.instantiate(RecoverPasswordRequest.class)
        .setUsername("no@one.com"),
    new RequestContext().addHeader("Authorization", "SSWS ${api_token}") ,
    null);
````

This is a pretty low-level API, What type of application are you building?  Maybe we can suggest an alternative that doesn't require much code to be written?

**Comment by garcger-blk** [comment]
Unfortunately, we have to handle all of the credential-related flows and can't use any of out-of-the-box Okta flows.

We're able to make the following calls successfully without having to specify an api_token (which we already specify via **okta.yam**l):

```java
authenticationClient.resetPassword(newPassword.toCharArray(), stateToken, null);
```

**&**
```java
ExtensibleResource body = client.instantiate(ExtensibleResource.class);
body.put("token", activationToken);
AuthenticationResponse authResponse = authenticationClient
	.getDataStore().http().setBody(token).post("/api/v1/authn", AuthenticationResponse.class);
```

**Comment by bdemers** [comment]
The Authentication SDK, does not use the API token directly. Our management SDK, which manages Okta resources, think CRUD APIs, can use it if it's configured.

It's also possible to call `/api/v1/authn/recovery/password` without an API token.
For example, using an [email factor](https://developer.okta.com/docs/reference/api/authn/#request-example-for-forgot-password-with-email-factor).

Does that help?

**Comment by garcger-blk** [comment]
We can't take that approach because we need the `recoveryToken` that's generated when there's no `factorType`.

Why do these calls work for us without _explicitly_ specifying an api_token?

```java
authenticationClient.resetPassword(newPassword.toCharArray(), stateToken, null);
```

```java
authenticationClient
	.getDataStore().http().setBody(token).post("/api/v1/authn", AuthenticationResponse.class);
```

**Comment by bdemers** [comment]
Most of the /authn api works without an API token as they all deal with the context of a user (and in most cases a state token)

This API is used in many places where it's not possible for the client to have an API token (for example a frontend javascript app or native mobile application)

**Comment by garcger-blk** [comment]
Sorry to beat a dead horse, but according to https://developer.okta.com/docs/reference/api/authn/#request-example-for-reset-password an API token is required even with a state token (hence the confusion):

```
curl -v -X POST \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: SSWS ${api_token}" \
-d '{
  "stateToken": "00lMJySRYNz3u_rKQrsLvLrzxiARgivP8FB_1gpmVb",
  "newPassword": "Ch-ch-ch-ch-Changes!"
}' "https://${yourOktaDomain}/api/v1/authn/credentials/reset_password"```
```

Regardless, I was able to get it to work via your management SDK (which we also use and have it configured with an api_token):

```java
ExtensibleResource body = authenticationClient.instantiate(ExtensibleResource.class);
body.put("username", "no@one.com");
AuthenticationResponse authResponse = /*authentication*/client.getDataStore().http().setBody(body)
		.post("/api/v1/authn/recovery/password",
				AuthenticationResponse.class);
```

### feature request
please allow OKTA_CLIENT_TOKEN for your auth SDK

**Comment by bdemers** [comment]
Understood @garcger-blk 
We could make this scenario easier to use.
Many of these operations depend on which state your user is in: https://github.com/okta/okta-auth-java/#authentication-state-machine

For some recover steps an API token is required along with a state token to ensure both the client and the user are allowed to make a given request.

I'd love to hear why you need to deal with the flows directly, send me a message at Brian.Demers at okta

**Comment by oanam** [comment]
> You have a couple of different options depending on the type of application you are building
> If you are using the /authn API for this request, you would need to include the SSWS token in this request.
> 
> https://github.com/okta/okta-auth-java/blob/master/api/src/main/java/com/okta/authn/sdk/client/AuthenticationClient.java#L287
> 
> Which would be something like:
> 
> ```java
> authenticationClient.recoverPassword(
>     authenticationClient.instantiate(RecoverPasswordRequest.class)
>         .setUsername("no@one.com"),
>     new RequestContext().addHeader("Authorization", "SSWS ${api_token}") ,
>     null);
> ```

Hi @bdemers,

Out team is also looking for a way to implement the above without sending an e-mail to the user - therefore the API token is required.

I have one question related to this: what is the recommended role of the service account used for generating the SSWS token here? 

I am trying to identify the least privileged option that can still do the job, as I'd prefer to avoid SUPER ADMIN, if at all possible.
I checked this list, but am still having trouble identifying what applies to the above:
https://help.okta.com/en/prod/Content/Topics/Adv_Server_Access/docs/asa-overview.htm

**Comment by bdemers** [comment]
There should be a couple of roles that work for you. See the "password resets" in this table: https://help.okta.com/en/prod/Content/Topics/Security/administrators-admin-comparison.htm#User
