### ISSUE TITLE
Primary authentication with trusted application not supported by SDK

### ISSUE THREAD

**Issue by oanam** [okta/okta-auth-java#77]
Hello, 

Our team is trying to implement the primary authentication with trusted application flow, as described here in the API docs: https://developer.okta.com/docs/reference/api/authn/#primary-authentication-with-trusted-application. 

We tried to use the Java Auth SDK (https://github.com/okta/okta-auth-java) to implement it, but it looks like this SDK does not support authentication via trusted application - the DefaultAuthenticationClientBuilder sets the client credentials resolver as a DisabledClientCredentialsResolver and does not allow setting the authorization mode - compare it to the ClientBuilder from the Management SDK: https://github.com/okta/okta-sdk-java, which does. 

We didn't find an implementation for the authentication with trusted application flow in the Management SDK, either. 

Is there any way we can implement authentication with a trusted application with any of the Java SDKs? For security reasons, we would like to avoid using the admin API token, and use the scoped OAuth 2.0 tokens (AuthorizationMode.PRIVATE_KEY).

How would you recommend we approach this?

Thank you, 
Oana

**Comment by bdemers** [comment]
Hi @oanam!

There are a few questions in here so I'll try to go through them. If I miss one just let us know!

> We tried to use the Java Auth SDK (https://github.com/okta/okta-auth-java) to implement it, but it looks like this SDK does not support authentication via trusted application - the DefaultAuthenticationClientBuilder sets the client credentials resolver as a DisabledClientCredentialsResolver and does not allow setting the authorization mode - compare it to the ClientBuilder from the Management SDK: https://github.com/okta/okta-sdk-java, which does.
>
> We didn't find an implementation for the authentication with trusted application flow in the Management SDK, either.

The Auth SDK doesn't directly support authorized clients.  As some of these requests can be made from an authorized or unauthorized client (in various situations).  The workaround for this is to include the additional auth header.

Take a look at the comment here: https://github.com/okta/okta-auth-java/issues/76#issuecomment-674116121
And let me know if that helps

> Is there any way we can implement authentication with a trusted application with any of the Java SDKs? For security reasons, we would like to avoid using the admin API token, and use the scoped OAuth 2.0 tokens (AuthorizationMode.PRIVATE_KEY).

As far as supporting Private key authentication, I'm not sure, I've asked another team to chime in on this. It doesn't look like it is supported, as we do not publish an OAuth scope for authentication: https://developer.okta.com/docs/guides/implement-oauth-for-okta/scopes/

On the Auth SDK side, the implementation would be the same, something like `.addHeader("Authorization", "Bearer ${access_token}")`, Though your application would need to manage the OAuth token.

> How would you recommend we approach this?

Usually, I'd recommend against using the Auth API and push you to an OAuth flow instead, as this removes many of these concerns and significantly reduces the code you need to write.  That said, I don't know any of the details of your use case, forgive me if that isn't helpful advice 😄

**Comment by oanam** [comment]
Thank you for the detailed response, Brian!

We try out the approach you suggested, with the Authorization header.

I have missed the fact that, indeed, there is no OAuth scope for authentication. 
It is unfortunate, because this means the authentication with a _trusted application_ can, in fact, only be implemented using an API token - which, to my understanding, is issued for a specific user, not for the actual application.

I don't think the OAuth flow can help us, given our requirements... We already have an internal service handling authorization, as well as an internal e-mailing service that we need to use, as well as requirements to support multiple brands in both UI and e-mails - therefore we're relying on the Okta APIs only for authentication and aspects linked to this (factors, password and authentication policies, etc.).

Thank you,
Oana

**Comment by bdemers** [comment]
I was thinking about this a bit more 🤔 

We could do something like: `authClient.trusted().authenticate(...)`, to avoid the need to handle the API token in your application. this "trusted" method would return a client configured with the API token the same way the Management SDK is configured. This would be functionally equivalent to the above workaround, but it would be a nicer API.

As for currently using an API token, you could create a service account user that reduced permissions and create an API token with that user.  This would limit the scope of what the API token can do.
